### ISSUE TITLE
Star Trek/X-Men

### ISSUE THREAD

**Issue by CoderHead** [UnicornSnuggler/Crossover-Roadmap#9]
The X-Men officially cross over into the Star Trek universe via a team-up in Star Trek/X-Men vol. 1!

https://marvel.fandom.com/wiki/Star_Trek_/_X-Men_Vol_1_1

> Now unless ya' want me to bob those pointy ears of yers, Mister Spock -- now would be a good time to take us to yer leader.
-- Wolverine

**Comment by UnicornSnuggler** [comment]
> Published by Marvel Comics as part of its short-lived Paramount Comics imprint, the book chronicles the first encounter between Captain James T. Kirk and the crew of the Enterprise (during the five-year mission of the original series) and members of the X-Men, who traveled through a dimensional rift chasing the mutant Proteus. The artwork was produced by Marc Silvestri, as well as several other artists from his studio, Top Cow Productions. This was the first of the Star Trek comic books published by Marvel for the Paramount Comics line, and it contains previews for several of the follow-up series.

[Wikipedia article](https://en.wikipedia.org/wiki/Star_Trek/X-Men)

While not the earliest occurrence of a Star Trek crossover, this is perhaps one of the _ better-known_ instances.  Pretty clearly a `Beta` lore archetype thanks to the magic of psionic space energy.

> Returning to the planet Delta Vega, site of the deaths of Lt. Cmdr. Gary Mitchell and Dr. Elizabeth Dehner, Captain Kirk and the crew of the Enterprise encounter a rift of psionic energy in space, through which travels a starship of Shi'ar design. The ship is quickly destroyed by the spatial anomaly, though not before Spock detects that it carried seven lifeforms of "near human" nature. A second, larger Shi'ar craft comes through the rift, which promptly fires an unusual projectile at the Enterprise: Gladiator of the Shi'ar Imperial Guard, who warns the Enterprise away from the planet and drives his point home by striking the ship's deflector shields, causing some actual damage to the vessel as a result.
